sudo: required
language: ruby
rvm:
  - 2.5.1
cache: bundler
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y curl git make ruby-bundler ruby-dev libxml2-dev libxslt-dev npm
  - travis_retry gem install bundler
  - travis_retry gem install nokogiri -v '1.8.5'
  - sudo bash -c "curl -L https://github.com/riboseinc/plantuml-install/raw/master/ubuntu.sh | bash"
  - travis_retry npm install puppeteer
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
    - PLANTUML_URL=http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
    - ENCRYPTION_LABEL=bb73481fab12
    - COMMIT_AUTHOR_EMAIL=travis-ci@ribose.com
script:
  - plantuml -testdot
  - make clean all
  - make publish
  - '[ "${TRAVIS_BRANCH}" = "master" ] && ./deploy.sh'
